#!/usr/bin/env python3
"""Refresh data/stars.js from the repos named in data/contributions.js.

contributions.js is hand-written and this script never touches it. stars.js is
machine-owned and rewritten wholesale, so a scheduled run can never collide
with an edit to the prose.

Usage:
    python3 scripts/refresh_stars.py [--check]

--check exits 1 if the file is out of date instead of writing it.
Set GITHUB_TOKEN (or GH_TOKEN) to lift the API rate limit from 60/hr to 5000/hr.
"""

import argparse
import datetime
import json
import os
import pathlib
import sys
import time
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRIBUTIONS = ROOT / "data" / "contributions.js"
STARS = ROOT / "data" / "stars.js"

HEADER = """\
/*
 * Generated by scripts/refresh_stars.py. Do not edit by hand.
 * Star counts for every repo named in contributions.js, refreshed weekly.
 */
"""


def load_contributions():
    text = CONTRIBUTIONS.read_text()
    marker = "window.CONTRIBUTIONS ="
    start = text.index(marker) + len(marker)
    return json.loads(text[start:].rstrip().rstrip(";"))


def fetch_stars(repo):
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}",
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "sainad2222.github.io-star-refresh",
        },
    )
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")

    with urllib.request.urlopen(request, timeout=30) as response:
        return json.loads(response.read())["stargazers_count"]


def render(stars, updated):
    body = json.dumps(
        {"updated": updated, "repos": dict(sorted(stars.items()))},
        indent=2,
        sort_keys=False,
    )
    return f"{HEADER}window.STARS = {body};\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if stars.js is out of date, write nothing")
    args = parser.parse_args()

    repos = sorted({entry["repo"] for entry in load_contributions()})

    # Keep the previous numbers so one failed request does not blank a repo.
    previous = {}
    if STARS.exists():
        text = STARS.read_text()
        marker = "window.STARS ="
        if marker in text:
            start = text.index(marker) + len(marker)
            previous = json.loads(text[start:].rstrip().rstrip(";")).get("repos", {})

    stars = {}
    failed = []
    for repo in repos:
        try:
            stars[repo] = fetch_stars(repo)
        except (urllib.error.URLError, KeyError, ValueError) as exc:
            failed.append(f"{repo}: {exc}")
            if repo in previous:
                stars[repo] = previous[repo]
        time.sleep(0.2)

    for message in failed:
        print(f"warning: {message}", file=sys.stderr)

    if not stars:
        print("error: no star counts retrieved, leaving stars.js alone", file=sys.stderr)
        return 1

    unchanged = stars == previous
    updated = datetime.date.today().isoformat()

    if args.check:
        if unchanged:
            print("stars.js is up to date")
            return 0
        print("stars.js is out of date")
        return 1

    if unchanged:
        print("no star counts changed")
        return 0

    STARS.write_text(render(stars, updated))
    for repo in repos:
        before = previous.get(repo)
        after = stars.get(repo)
        if before != after:
            print(f"{repo}: {before} -> {after}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
